### ISSUE TITLE
Playback fails

### ISSUE THREAD

**Issue by MasterOfPuppets** [willforde/plugin.video.metalvideo#1]
Playback fails in any category.
No videos can be played.
I went to your website, and no videos show up there too.

Thank you

**Comment by willforde** [comment]
Thanks for lettting me know.
I don't have any control over the site I just create the kodi addon to access it.
Hopefully the site will be back working soon.

I am currently making a lot of changes to this addon and the backend script "codequick".  So only the addon in the official kodi repo should be used at the moment.

**Comment by MasterOfPuppets** [comment]
thanks for your reply. I'm not sure what version I'm using but I'll try it
this evening.

A Qui, 22/12/2016, 09:34, William Forde <notifications@github.com> escreveu:
